server:
  port: 8888

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: r1
              uri: http://localhost:8081/
              predicates:
                - Path=/customers/**


            - id: r2
              uri: http://localhost:8082/
              predicates:
                - Path=/products/**


      discovery:
        enabled: false